name: Tests

on:
  - pull_request
  - push

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5

      - name: Git checkout
        uses: actions/checkout@v4

      - name: go testing
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: travellingkiwi/sbam

      - name: Build
        run: make build
